"""Add container_selector to scraper_sites

Revision ID: c81a67917f65
Revises: 8ce93fb7d600
Create Date: 2026-03-10 20:08:44.906791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81a67917f65'
down_revision = '8ce93fb7d600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_selector', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_sites', schema=None) as batch_op:
        batch_op.drop_column('container_selector')

    # ### end Alembic commands ###
